# Fetching the latest node image on alpine linux
FROM node:alpine

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
RUN #npm install

# Starting our application
CMD npm start
