version: "3"

services:
    php:
        build:
            context: docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - .:/var/www

    postgresql:
        image: postgres:15.3
        container_name: awsdeveloper-db
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT:-5432}:5432"

    postgresql-test:
        image: postgres:15.3
        container_name: awsdeveloper-test-db
        environment:
            POSTGRES_DB: "awsdeveloper_test"
            POSTGRES_ROOT_PASSWORD: "secret"
            POSTGRES_USER: "awsdevelopertest"
            POSTGRES_PASSWORD: "secret"
        ports:
            - "5435:5435"
        command: -p 5435

    frontend:
        build:
            context: frontend
        image: frontend
        volumes:
            - ./frontend/:/app
            - /app/node_modules
        ports:
            - "3000:3000"

    nginx:
        container_name: nginx
        build:
            context: docker/nginx
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"

volumes:
    db-data:
